export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080'
export const WS_BASE_URL = import.meta.env.VITE_WS_BASE_URL || 'ws://localhost:8080'

export const QUERY_KEYS = {
  sprite: ['legacy', 'sprite'] as const,
  spriteState: ['legacy', 'sprite', 'state'] as const,
  lifeSnapshot: ['life', 'snapshot'] as const,
  lifeJournal: ['life', 'journal'] as const,
  lifeAutonomy: ['life', 'autonomy'] as const,
  modelConfig: ['life', 'model', 'config'] as const,
  cognition: ['legacy', 'sprite', 'cognition'] as const,
  memory: ['legacy', 'sprite', 'memory'] as const,
  memoryVisualization: ['legacy', 'sprite', 'memory', 'visualization'] as const,
  evolution: ['legacy', 'sprite', 'evolution'] as const,
  evolutionDashboard: ['legacy', 'sprite', 'evolution', 'dashboard'] as const,
  emotions: ['legacy', 'sprite', 'emotions'] as const,
  emotionDashboard: ['legacy', 'sprite', 'emotions', 'dashboard'] as const,
  health: ['legacy', 'sprite', 'health'] as const,
  devices: ['legacy', 'sprite', 'devices'] as const,
  backup: ['legacy', 'sprite', 'backup'] as const,
  agentWorkers: ['legacy', 'agent', 'workers'] as const,
  teamSprites: ['legacy', 'team', 'sprites'] as const,
  teamSessions: ['legacy', 'team', 'sessions'] as const,
  collaborationStatus: ['legacy', 'team', 'status'] as const,
  skills: ['skills'] as const,
  skill: ['skill'] as const,
  mcpServerStatus: ['mcp', 'server'] as const,
  mcpClientStatus: ['mcp', 'client'] as const,
  mcpClientTools: ['mcp', 'client', 'tools'] as const,
} as const

export const REFRESH_INTERVALS = {
  spriteState: 30000,
  lifeSnapshot: 10000,
  lifeJournal: 15000,
  lifeAutonomy: 10000,
  cognition: 15000,
  memory: 60000,
  evolution: 120000,
  emotions: 60000,
  health: 60000,
  devices: 30000,
  agentWorkers: 15000,
  teamSprites: 30000,
  teamSessions: 15000,
  collaborationStatus: 30000,
  skills: 30000,
  mcpServerStatus: 15000,
  mcpClientStatus: 15000,
  mcpClientTools: 30000,
} as const
